### ISSUE TITLE
Merge and Prepare Files for Data Entry

### ISSUE THREAD

**Issue by KasiaPaloma** [GreenfieldAdvisors/IKB-MS#2]
Project Lead works with Roget/KR to prepare the files and folders that will be referenced by the database. Complete this task when folders are ready for the Data Entry team.

**Comment by KasiaPaloma** [comment]
@jessGA is using R to create the folders and I am merging any necessary folders. Once ready the folders are moved to the appropriate Loan File Location for the DB.
The following location is being used to track any oddities in the files. Could be used for the scope change log since we didn't expect this much manual handling of loan files.
"P:\2018\18-0805 IKB v MS\Loan Files\Loan File QC.xlsx"

**Comment by KasiaPaloma** [comment]
@Matt006 here is the update on the loan files. 
*Loan File location = P:\2018\18-0805 IKB v MS\Database\IKB-MSDB_LoanFiles

1. The location I mentioned in the previous comment is updated with everything I've done manually. 
2. The following location still has loans left to merge and move into the Loan File location 
P:\2018\18-0805 IKB v MS\Loan Files\Renamed Deliveries
Once @Roget168 is back he can use his scripts to clean this up. 
3. The following spreadsheet was being used to track loans I was prioritizing to move and which are already in the Loan File location
"P:\2018\18-0805 IKB v MS\Loan Files\Random Sample Files\MS Loan File Delivery 8.27.18.xlsx"

Data Entry is good for a couple more days but I'd prioritize completing this on Tuesday.

**Comment by Matt006** [comment]
@Roget168 is taking a look at no. 2 to see what, if any, can be done by script.  I will do the remainder manually - likely Wednesday.

**Comment by Roget168** [comment]
@Matt006, take a look at P:\2018\18-0805 IKB v MS\Working\Matthew\RenamePhase1 and let me know if everything looks good.  If so, I will try and run the script to merge the PDFs in each of the loan directories.

**Comment by Matt006** [comment]
This looks good Roget, please proceed.

**Comment by Matt006** [comment]
This is complete: 1129 files are in the DB Loan File location.  Please proceed with updating the DB (issue #1).  

Many thanks to @Roget168 for handling this! 🥇

**Comment by ElizLuff** [comment]
@Matt006 can this issue be closed?
